baseURL = "https://zanhzoker.github.io/fcaj-report/"

relativeURLs = false
canonifyURLs = true

# English is the default language; Vietnamese pages use the .vi.md suffix.
defaultContentLanguage = "en"

# Hugo theme
theme = "hugo-theme-learn"

# Required for the theme search function
[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "workshop"

# Để trống vì chưa cần nút chỉnh sửa nội dung trên GitHub
editURL = ""

description = "AWS FCAJ Internship Report - E-commerce Recommendation Project and Data Engineering"
author = "Trần Uy Danh"

showVisitedLinks = true
disableBreadcrumb = false
disableNextPrev = false

[Languages]

# English
[Languages.en]
title = "Internship Report - Trần Uy Danh"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Facebook Group"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 21

# Vietnamese
[Languages.vi]
title = "Báo cáo thực tập"
weight = 2
languageName = "Tiếng Việt"

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-aws'></i> AWS Study Group - Blog"
identifier = "AWS Study Group"
url = "https://awsstudygroup.com"
weight = 20

[[Languages.vi.menu.shortcuts]]
name = "<i class='fab fa-facebook'></i> AWS Study Group - Nhóm Facebook"
identifier = "AWS Study Group FB"
url = "https://www.facebook.com/groups/awsstudygroupfcj"
weight = 21

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true
